/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_qw3rtrun_libretro_cb_EnvironmentNative */

#ifndef _Included_org_qw3rtrun_libretro_cb_EnvironmentNative
#define _Included_org_qw3rtrun_libretro_cb_EnvironmentNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    getVariable
 * Signature: (Ljava/lang/String;)Lorg/qw3rtrun/libretro/struct/Variable;
 */
JNIEXPORT jobject JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_getVariable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    setVariables
 * Signature: (Ljava/util/Collection;)V
 */
JNIEXPORT void JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_setVariables
(JNIEnv *, jobject, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    isVariablesUpdated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_isVariablesUpdated
  (JNIEnv *, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    getLogInterface
 * Signature: ()Lorg/qw3rtrun/libretro/cb/LogCallback;
 */
JNIEXPORT jobject JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_getLogInterface
  (JNIEnv *, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    setControllerInfo
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_setControllerInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    getCurrentSoftwareFrameBuffer0
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_getCurrentSoftwareFrameBuffer0
  (JNIEnv *, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    setPixelFormat0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_setPixelFormat0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    setInputDescriptors
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_setInputDescriptors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_qw3rtrun_libretro_cb_EnvironmentNative
 * Method:    setKeyboardCallback
 * Signature: (Lorg/qw3rtrun/libretro/cb/KeyboardCallback;)V
 */
JNIEXPORT void JNICALL Java_org_qw3rtrun_libretro_cb_EnvironmentNative_setKeyboardCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
